version: 2
  jobs:
    build:
      docker:
        - image: circleci/node:8.11.1
      working_directory: ~/alex
      environment:
        ALEX_BUILD_DIR: ~/alex
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - "xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"
        - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
        - deploy:
            name: deploy
            command: |
              if [ "${CIRCLE_BRANCH}" = "master" ]; then
                rsync -avce ssh $ALEX_BUILD_DIR fancn21th_gmail_com@34.73.123.46:/data/www
              else
                echo "Not master branch, dry run only"
              fi